plugins {
    id 'org.openapi.generator'
    id 'uk.gov.justice.service.laa.laa-spring-boot-gradle-plugin'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation('org.springframework.boot:spring-boot-starter-web') {
        exclude group: 'com.google.code.gson', module: 'gson'
    }

    implementation 'org.springframework.security:spring-security-core'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.9.0'
    implementation 'org.openapitools:jackson-databind-nullable:0.2.11'

}

publishing {
    publications {
        gpr(MavenPublication) {
            from(components.java)
        }
    }
}

sourceSets.main.java.srcDirs += ['generated/src/main/java']

checkstyleMain.exclude("*")

openApiGenerate {
    generatorName = "spring"
    inputSpec = "$rootDir/data-access-api/open-api-specification.yml".toString()
    outputDir = "$rootDir/data-access-api/generated".toString()
    apiPackage = "uk.gov.justice.laa.dstew.access.api"
    invokerPackage = "uk.gov.justice.laa.dstew.access.invoker"
    modelPackage = "uk.gov.justice.laa.dstew.access.model"
    configOptions = [
            generateBuilders    : "true",
            interfaceOnly       : "true", // This will only generate interfaces, not implementations
            openApiNullable     : "false", // Keep nullable scalar properties as boxed Java types
            serializableModel   : "true",
            skipDefaultInterface: "true",
            useJakartaEe        : "true",
            useSpringBoot4      : "true",
            useTags             : "true",
    ]
    globalProperties = [
            models              : "", // omitting `supportingFiles` prevents generation of
            apis                : "", // pom.xml, README.md, ApiUtil.java, etc.
    ]
}

tasks.named('openApiGenerate') {
    inputs.files(fileTree(projectDir) {
        include '**/*.yml'
        exclude 'build/**', 'generated/**'
    }).withPathSensitivity(PathSensitivity.RELATIVE)
}

compileJava.dependsOn('openApiGenerate')

clean {
    delete("$rootDir/data-access-api/generated")
}

// disable for overall project when running a build
tasks.named('bootJar') {
    enabled = false
}

tasks.named('bootRun') {
    enabled = false
}

tasks.named('bootBuildImage') {
    enabled = false
}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
