openapi: "3.0.0"
info:
  title: Applications API
  version: 1.0.0

security:
  - BearerAuth: []

paths:
  /api/v0/applications:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications"
  /api/v0/applications/{id}:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}"
  /api/v0/caseworkers:
    $ref: "./open-api-caseworkers/resources.yml#/paths/~1api~1v0~1caseworkers"
  /api/v0/applications/assign:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1assign"
  /api/v0/applications/{id}/unassign:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}~1unassign"
  /api/v0/applications/{id}/history-search:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}~1history-search"
  /api/v0/applications/{id}/decision:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}~1decision"
  /api/v0/applications/{id}/auto-grant-outcome:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}~1auto-grant-outcome"
  /api/v0/applications/{id}/certificate:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}~1certificate"
  /api/v0/individuals:
    $ref: "./open-api-individuals/resources.yml#/paths/~1api~1v0~1individuals"
  /api/v0/applications/{id}/notes:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}~1notes"
  /api/v0/applications/{id}/upload-document:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}~1upload-document"
  /api/v0/applications/{id}/download-document/{documentId}:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}~1download-document~1{documentId}"
  /api/v0/applications/{id}/update-document:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}~1update-document"
  /api/v0/applications/{id}/delete-document:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}~1delete-document"
  /api/v0/applications/{id}/prior-authority:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1applications~1{id}~1prior-authority"
  /api/v0/applications/{applicationId}/prior-authority/draft:
    $ref: "./open-api-prior-authority/resources.yml#/paths/~1api~1v0~1applications~1{applicationId}~1prior-authority~1draft"
  /api/v0/prior-authorities/{priorAuthorityId}:
    $ref: "./open-api-prior-authority/resources.yml#/paths/~1api~1v0~1prior-authorities~1{priorAuthorityId}"
  /api/v0/prior-authorities/{priorAuthorityId}/submit:
    $ref: "./open-api-prior-authority/resources.yml#/paths/~1api~1v0~1prior-authorities~1{priorAuthorityId}~1submit"
  /api/v0/prior-authorities/{priorAuthorityId}/documents:
    $ref: "./open-api-prior-authority/resources.yml#/paths/~1api~1v0~1prior-authorities~1{priorAuthorityId}~1documents"
  /api/v0/sds/health:
    $ref: "./open-api-applications/resources.yml#/paths/~1api~1v0~1sds~1health"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ApplicationResponse:
      $ref: "./open-api-applications/components.yml#/components/schemas/ApplicationResponse"
    ApplicationCreateRequest:
      $ref: "./open-api-applications/components.yml#/components/schemas/ApplicationCreateRequest"
    ApplicationUpdateRequest:
      $ref: "./open-api-applications/components.yml#/components/schemas/ApplicationUpdateRequest"
    ApplicationSummaryResponse:
      $ref: "./open-api-applications/components.yml#/components/schemas/ApplicationSummaryResponse"
    ApplicationSummary:
      $ref: "./open-api-applications/components.yml#/components/schemas/ApplicationSummary"
    CaseworkerResponse:
      $ref: "./open-api-caseworkers/components.yml#/components/schemas/CaseworkerResponse"
    CaseworkersResponse:
      $ref: "./open-api-caseworkers/components.yml#/components/schemas/CaseworkersResponse"
    CaseworkerAssignRequest:
      $ref: "./open-api-caseworkers/components.yml#/components/schemas/CaseworkerAssignRequest"
    ApplicationDomainEventResponse:
      $ref: "./open-api-applications/components.yml#/components/schemas/ApplicationDomainEventResponse"
    PagingResponse:
      $ref: "./open-api-common/components.yml#/components/schemas/PagingResponse"
    MakeDecisionRequest:
      $ref: "./open-api-applications/components.yml#/components/schemas/MakeDecisionRequest"
    AutoGrantOutcomeRequest:
      $ref: "./open-api-applications/components.yml#/components/schemas/AutoGrantOutcomeRequest"
    IndividualResponse:
      $ref: "./open-api-individuals/components.yml#/components/schemas/IndividualResponse"
    IndividualsResponse:
      $ref: "./open-api-individuals/components.yml#/components/schemas/IndividualsResponse"
    CreateNoteRequest:
      $ref: "./open-api-applications/components.yml#/components/schemas/CreateNoteRequest"
    ApplicationNoteResponse:
      $ref: "./open-api-applications/components.yml#/components/schemas/ApplicationNoteResponse"
    ApplicationNotesResponse:
      $ref: "./open-api-applications/components.yml#/components/schemas/ApplicationNotesResponse"
    DocumentUploadResponse:
      $ref: "./open-api-applications/components.yml#/components/schemas/DocumentUploadResponse"
    DocumentDownloadResponse:
      $ref: "./open-api-applications/components.yml#/components/schemas/DocumentDownloadResponse"
    DocumentUpdateResponse:
      $ref: "./open-api-applications/components.yml#/components/schemas/DocumentUpdateResponse"
    SdsHealthResponse:
      $ref: "./open-api-applications/components.yml#/components/schemas/SdsHealthResponse"
    PriorAuthorityType:
      $ref: "./open-api-applications/components.yml#/components/schemas/PriorAuthorityType"
    BillingType:
      $ref: "./open-api-applications/components.yml#/components/schemas/BillingType"
    CounselType:
      $ref: "./open-api-applications/components.yml#/components/schemas/CounselType"
    TimeRequested:
      $ref: "./open-api-applications/components.yml#/components/schemas/TimeRequested"
    Apportionment:
      $ref: "./open-api-applications/components.yml#/components/schemas/Apportionment"
    ExpertCosts:
      $ref: "./open-api-applications/components.yml#/components/schemas/ExpertCosts"
    ExpertDetails:
      $ref: "./open-api-applications/components.yml#/components/schemas/ExpertDetails"
    CounselDetails:
      $ref: "./open-api-applications/components.yml#/components/schemas/CounselDetails"
    DisbursementDetails:
      $ref: "./open-api-applications/components.yml#/components/schemas/DisbursementDetails"
    CreatePriorAuthorityRequest:
      $ref: "./open-api-applications/components.yml#/components/schemas/CreatePriorAuthorityRequest"
    CreatePriorAuthorityResponse:
      $ref: "./open-api-applications/components.yml#/components/schemas/CreatePriorAuthorityResponse"
    SavePriorAuthorityDraftRequest:
      $ref: "./open-api-prior-authority/components.yml#/components/schemas/SavePriorAuthorityDraftRequest"
    SavePriorAuthorityDraftResponse:
      $ref: "./open-api-prior-authority/components.yml#/components/schemas/SavePriorAuthorityDraftResponse"
    AttachPriorAuthorityDocumentResponse:
      $ref: "./open-api-prior-authority/components.yml#/components/schemas/AttachPriorAuthorityDocumentResponse"
    SubmitPriorAuthorityDraftResponse:
      $ref: "./open-api-prior-authority/components.yml#/components/schemas/SubmitPriorAuthorityDraftResponse"
    PriorAuthorityResponse:
      $ref: "./open-api-prior-authority/components.yml#/components/schemas/PriorAuthorityResponse"
