pluginManagement {
    repositories {
        maven {
            name = "sonatypeSnapshots"
            url = uri('https://central.sonatype.com/repository/maven-snapshots/')
            mavenContent {
                snapshotsOnly()
            }
        }
        maven { url = uri("https://plugins.gradle.org/m2/") }
        gradlePluginPortal()
    }

    plugins {
        id 'uk.gov.justice.service.laa.laa-spring-boot-gradle-plugin' version '3.0.1'
        id 'org.openapi.generator' version '7.24.0'
    }
}

rootProject.name = 'laa-data-access-api'

include 'data-access-api'
include 'data-access-service'
include 'data-access-service-axon'
include 'data-access-shared'
include 'data-access-mass-generator'
